version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mstfymrtc
      MONGO_INITDB_ROOT_PASSWORD: Admin1224

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mstfymrtc
      ME_CONFIG_MONGODB_ADMINPASSWORD: Admin1224